### ISSUE TITLE
RuleEngineApplication 启动报错

### ISSUE THREAD

**Issue by ccwxl** [jetlinks/jetlinks#5]
`org/jetlinks/rule/engine/cluster/scheduler/DefaultRuleEngineScheduler.java:76
       //加载所有任务
        loadAllRule();
`
这加载时报错. 我看 
org.jetlinks.cloud.rule.RuleEngineAutoDeployProcess 部署在项目启动完成后进行的, 但是加载在未启动完就开始. 是这样吗?
![image](https://user-images.githubusercontent.com/13701232/62026051-75f73e00-b20c-11e9-8937-57a9f53f0925.png)

**Comment by AllenFeng-China** [comment]
同样报错路过。。。。
目前这个项目应该还在开发中。

**Comment by zhou-hao** [comment]
莫慌，正在搞更简单的演示版

**Comment by zhou-hao** [comment]
https://github.com/jetlinks/jetlinks-platform 先玩玩这个

**Comment by AllenFeng-China** [comment]
**ok**
