### ISSUE TITLE
这么多子项目，感觉有点乱，有没有比较清晰的关系图？

### ISSUE THREAD

**Issue by inprise1980** [jetlinks/jetlinks#6]
这么多子项目，感觉有点乱，有没有比较清晰的关系图？ 比如jetlinks-platform 与letlinks-iot-cloud的关系？或与其他子项目的关系？

**Comment by Lind-pro** [comment]
又来了一个妄图几分钟就看懂一个设计了几年的系统。。

**Comment by zhou-hao** [comment]
@inprise1980  暂时没有。等社区版发布吧。

**Comment by inprise1980** [comment]
开源不是想让更多人参与进来使用与反馈？ 能提供详细的安装说明与使用说明不是更容易能让人上手？

**Comment by zhou-hao** [comment]
@inprise1980 讲道理是这样的。还需要时间。

**Comment by inprise1980** [comment]
@Lind-pro   大神，您老哪只眼睛看见我想几分钟看懂一个设计了几年的系统？

**Comment by inprise1980** [comment]
@Lind-pro 您老可以做个调查，看在github上刚查到jetlink项目时，看到这么多子项目，是否第一反映是想先搞清楚他们之间的关系，如何有一张简单的关系图或是详细的说明，是否更有助于使用者的理解与使用？

**Comment by Lind-pro** [comment]
我就是个路人，我意识到错误了。@inprise1980
