### ISSUE TITLE
为什么自己实现Eventbus？

### ISSUE THREAD

**Issue by chanlk9527** [jetlinks/jetlinks#9]
作者你好！

这个项目一个特点是事件驱动，系统可以说是通过订阅各种消息跑起来的，
这包括代码上写好的订阅和动态加载出来的订阅逻辑，
其中核心功能规则引擎我看也是很大的依赖了Eventbus结合reactorQL做的。
（不知道我理解得对不对）

我看这一块蛮复杂的，数据是存储在redis list里，自己在上层构建了一整套很完备的事件系统
包括了支持多层级通配符的Topic 、多种订阅方式、payload编解码等等很多特性

给扎实的技术点赞！请问为什么不采用现成的MQ中间件而要自己实现，如RocketMQ？
是因为响应式的原因？还是有业务特性无法被支持？还是性能不满足？

期待您的解答！

**Comment by zhou-hao** [comment]
1. Eventbus是一个抽象的设计，用于统一提供响应式细粒度的事件分发功能。
2. MQ较难实现海量topic 以及频繁细粒度订阅发布。（你也可以使用MQ来作为Eventbus的实现）
3.  大部分请求其实都是进程内事件传递。所以mq并不是必须，jetlinks作为通用平台，原则上是尽量减少对外部中间件的依赖，预留相应拓展点由不同的场景去拓展。

1. 社区版中目前已经弃用了eventbus的集群支持，只支持进程内传递事件。（你可以尝试使用RpcManager来实现集群通信）
2. 目前版本数据没有存储到`redis list`了，性能较低。

**Comment by chanlk9527** [comment]
基本明白了，感谢解答！
针对 4.去除了eventbus的集群支持，所以社区版本是不支持集群部署的原因之一是吧？

另外，想请问一下这种框架设计和编码的能力是如何锻炼出来的，
像这个eventbus、规则引擎、reactorQL、物模型编解码、hsweb框架等等我觉得都写得很优秀，
业务CRUD代码写多了还是很仰慕能够写这样代码的大佬哈哈！

**Comment by zhou-hao** [comment]
去除了eventbus的集群支持是因为之前的集群支持实现并不好，经过多次迭代 没有达到预期效果、后来在企业版实现了新的集群eventbus支持。但是现阶段不适合开放到社区版。
底层的集群支持是开源的，见 ClusterConfiguration。只是社区版中对应的功能没有进行适配，如：保存网络组件时的集群通知等。社区版要实现集群其实不难。

无他,惟手熟尔!

**Comment by chanlk9527** [comment]
感谢解答！
